
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vidparsepro.desktop'
    compileSdk 33

    defaultConfig {
        applicationId "com.vidparsepro.desktop"
        minSdk 24
        targetSdk 33
        def appVersion = System.getenv("APP_VERSION") ?: "1.3.9"
        def versionParts = appVersion.tokenize('.').collect { it as int }
        def versionCodeValue = 1
        if (versionParts.size() >= 3) {
            versionCodeValue = versionParts[0] * 10000 + versionParts[1] * 100 + versionParts[2]
        }
        versionCode versionCodeValue
        versionName appVersion
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'org.mozilla.geckoview:geckoview:147.0.20260212191108'
}
